parameters:
  - name: checkovArgs
    type: string
  - name: eslzEnvs
    type: object
  - name: rootEnvFolder
    type: string
  - name: terraformVersion
    type: string
  - name: terragruntVersion
    type: string

stages: 
- ${{ each eslzEnv in parameters.eslzEnvs }}:  
  - stage: ${{ eslzEnv.envName }}_Plan_${{ eslzEnv.multiRunID }}
    condition: always()
    dependsOn: []
    jobs:
      - job: InitJob
        pool: ${{ eslzEnv.pool }}
        steps:
          - checkout: none

          - bash: |
              if [[ $(Build.Reason) == "PullRequest" ]]; then
                  sourceBranch=$(echo $(System.PullRequest.SourceBranch) | sed 's|refs/heads/||')
                  echo "PullRequest build triggered from $sourceBranch"
              else
                  sourceBranch=$(Build.SourceBranchName)
                  echo "Manual build triggered from $sourceBranch"
              fi
              defaultBranch=$(curl -s -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -H "Content-Type: application/json" "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)?api-version=7.1-preview.1" | jq -r .defaultBranch | sed 's|refs/heads/||')
              changedFiles=$(curl -s -H "Authorization: Bearer $SYSTEM_ACCESSTOKEN" -H "Content-Type: application/json" "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.ID)/diffs/commits?baseVersion=$defaultBranch&targetVersion=$sourceBranch&api-version=7.1" | jq '.changes[].item.path')
              echo "$LAYERS_JSON" | jq -r '.[]' | while read -r layername; do
                  foldertocheck="${{ eslzEnv.envName }}/$layername/"
                  if [[ "$changedFiles" =~ $foldertocheck ]]; then
                      echo "Changes detected in the folder : (${{ eslzEnv.envName }}/$layername/)."
                      echo "##vso[task.setvariable variable=RepoChange$layername;isOutput=true]true"
                  else
                      echo "No changes detected in the folder : (${{ eslzEnv.envName }}/$layername/)."
                      echo "##vso[task.setvariable variable=RepoChange$layername;isOutput=true]false"
                  fi
              done

              for file in $(echo "$changedFiles" | tr -d '"'); do
                  filename=$(basename "$file")
                  if [[ "$filename" == "root.hcl" || "$filename" == "terragrunt.hcl" || "$filename" == *.sh ]]; then
                      echo "Restricted file change detected: $filename"
                      echo "##vso[task.setvariable variable=RestrictedFileChange;isOutput=true]true"
                      break
                  fi
              done
            name: GitDiffTask
            failOnStderr: True
            env:
              LAYERS_JSON: ${{ convertToJson(eslzEnv.layers) }}
              SYSTEM_ACCESSTOKEN: $(System.AccessToken)

      - job: RestrictedFilesValidation
        displayName: 'Manual Validation for Restricted Files'
        pool: server
        dependsOn: InitJob
        condition: and(succeeded(), eq(dependencies.InitJob.outputs['GitDiffTask.RestrictedFileChange'], 'true'))
        steps:
          - task: ManualValidation@1
            name: CheckRestrictedFilesChanges
            inputs:
              notifyUsers: ''
              approvers: 'Project Collection Administrators'
              instructions: 'Please review the changes in the restricted files (root.hcl, terragrunt.hcl, or shell scripts) before proceeding with the plan. If you are sure about the changes, please approve this step to continue.'
              onTimeout: 'reject'
              timeoutInMinutes: 1440

      - template: /terragrunt-multi-envs/templates/job-terragruntplan-template.yaml@templates
        parameters:
          serviceConnection: ${{ eslzEnv.serviceConnection }}
          eslzEnvFolder: ${{ eslzEnv.envName }}
          layers: ${{ eslzEnv.layers }}
          checkovArgs: ${{ parameters.checkovArgs }}
          eslzEnvPool: ${{ eslzEnv.pool }}
          rootEnvFolder: ${{ parameters.rootEnvFolder }}
      - job: PostPlanJob
        dependsOn:
        - InitJob
        - ${{ each layer in eslzEnv.layers }}:
          - TerragruntPlan_${{ eslzEnv.envName }}_${{ layer }}
        condition: always()  
        pool: 
          name: ${{ eslzEnv.pool }}
        steps:
          - checkout: none
          - task: DownloadBuildArtifacts@1
            name: DownloadPlan
            inputs:
              buildType: current
              downloadType: specific
              itemPattern: "*/plan*.txt"
              downloadPath: '$(Agent.TempDirectory)'
          - bash: |
              # echo "##vso[task.setvariable variable=PlanChange;isOutput=true]false"
              echo "$LAYERS_JSON" | jq -r '.[]' | while read -r layername; do
                if [[ -f $(Agent.TempDirectory)/plan_${{ eslzEnv.envName }}_$layername/plan_$layername.txt ]]; then
                  planvar=$(cat $(Agent.TempDirectory)/plan_${{ eslzEnv.envName }}_$layername/plan_$layername.txt)

                  if [[ "$planvar" =~ "No changes. Your infrastructure matches the configuration." ]]; then
                        echo "No Changes in plan detected in $layername)."
                        # echo "##vso[task.setvariable variable=PlanChange;isOutput=true]false"
                  else
                        echo "Changes in plan detected in $layername)."
                        echo "##vso[task.setvariable variable=PlanChange;isOutput=true]true"
                    fi

                  # if echo "$planvar" | grep -q "Plan:.*to add"; then
                  #   echo "Changes in plan detected in $layername)."
                  #   changes_detected=true
                  # elif echo "$planvar" | grep -q "Plan:.*to change"; then
                  #   echo "Changes in plan detected in $layername)."
                  #   changes_detected=true
                  # elif echo "$planvar" | grep -q "Plan:.*to destroy"; then
                  #   echo "Changes in plan detected in $layername)."
                  #   changes_detected=true
                  # else
                  #   echo "No Changes in plan detected in $layername)."
                  #   changes_detected=false
                  # fi

                  # echo "##vso[task.setvariable variable=PlanChange;isOutput=true]$changes_detected"
                fi
              done
            name: CheckPlanChangeTask
            failOnStderr: True
            env:
              LAYERS_JSON: ${{ convertToJson(eslzEnv.layers) }}
              
  - stage: ${{ eslzEnv.envName }}_Apply_${{ eslzEnv.multiRunID }}
    pool: ${{ eslzEnv.pool }}
    dependsOn: ${{ eslzEnv.envName }}_Plan_${{ eslzEnv.multiRunID }}
    condition: and(succeeded(), eq(dependencies.${{ eslzEnv.envName }}_Plan_${{ eslzEnv.multiRunID }}.outputs['PostPlanJob.CheckPlanChangeTask.PlanChange'], 'true'))
    jobs:
      - template: /terragrunt-multi-envs/templates/job-terragruntapply-template.yaml@templates
        parameters:
          serviceConnection: ${{ eslzEnv.serviceConnection }}
          eslzEnvFolder: ${{ eslzEnv.envName }}
          layers: ${{ eslzEnv.layers }}
          eslzEnvPool: ${{ eslzEnv.pool }}
          multiRunID: ${{ eslzEnv.multiRunID }}
          rootEnvFolder: ${{ parameters.rootEnvFolder }}
          terraformVersion: ${{ parameters.terraformVersion }} 
          terragruntVersion: ${{ parameters.terragruntVersion }}